# ref: https://github.com/node-red/node-red-docker/tree/master#docker-stack--docker-compose

version: '3.7'

services:
  node-red:
    build: ./node-red/
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "1880:1880"
    container_name: "nodered-docker-compose"
    volumes:
      - ./_node-red:/data
      # - ./tmp:/tmp/docker
    # restart: always
